/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.BienDongDAO;
import DAO.BoPhanDAO;
import DAO.ChucVuDAO;
import DAO.HopDongDAO;
import DAO.LyLichDAO;
import Helpers.Format;
import Helpers.ImageHelper;
import Helpers.MessageDialogHelper;
import Helpers.TableDesign;
import Model.BienDongNhanSu;
import Model.BoPhan;
import Model.ChucVu;
import Model.HopDongLaoDong;
import Model.LyLich;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class FrBienDong extends javax.swing.JInternalFrame {

    /**
     * Creates new form BienDong
     */
    public FrBienDong() {
        initComponents();
        LoadComboBox();
        initTable();
        LoadTable();
        DesignTable();
    }

    private DefaultTableModel tblmodel;
    private byte[] personalImage;
    SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
    private Home home;

    private void initTable() {
        tblmodel = new DefaultTableModel();
        String[] header = new String[]{"Mã nhân viên",
            "Ngày hiện lực",
            "Tên chức vụ cũ",
            "Tên phòng ban cũ",
            "Lương cơ bản cũ",
            "Tên chức vụ mới",
            "Tên phòng ban mới",
            "Lương cơ bản mới"};
        tblmodel.setColumnIdentifiers(header);
        tblBoTri.setModel(tblmodel);
        TableDesign.Design(tblBoTri);
    }

    private void LoadTable() {
        try {
            BienDongDAO dao = new BienDongDAO();
            List<BienDongNhanSu> list;
            list = dao.FindAllBoTri();
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),
                    it.getNgayHieuLuc(),
                    it.getTenCV_C(),
                    it.getTenBP_C(),
                    Format.FormatNumber(it.getHeSoLuong_C()),
                    it.getTenCV_M(),
                    it.getTenBP_M(),
                    Format.FormatNumber(it.getHeSoLuong_M())});
            });
            tblmodel.fireTableDataChanged();
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }

    private void LoadComboBox() {
        try {
            cbbBP.removeAllItems();
            BoPhanDAO dao1 = new BoPhanDAO();
            List<BoPhan> list1 = dao1.FindAllBoPhan();
            list1.forEach(it -> {
                cbbBP.addItem(it.getTenPB());
            });

            cbbCV.removeAllItems();
            ChucVuDAO dao2 = new ChucVuDAO();
            List<ChucVu> list2 = dao2.FindAllChucVu();
            list2.forEach(it -> {
                cbbCV.addItem(it.getTenCV());
            });

            cbbMaNV.removeAllItems();
            HopDongDAO dao3 = new HopDongDAO();
            List<HopDongLaoDong> list3 = dao3.FindAll();
            list3.forEach(it -> {
                cbbMaNV.addItem(it.getMaNV());
            });
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }

    }

    private void DesignTable(){
        TableDesign.Design(tblBoTri);
        //định dạng số sang bên phải
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tblBoTri.setModel(tblmodel);
        tblBoTri.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        tblBoTri.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        
        tblBoTri.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblBoTri.getColumnModel().getColumn(6).setPreferredWidth(100);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCV_C = new javax.swing.JLabel();
        lblBP_C = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHSL_M = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCV_C = new javax.swing.JTextField();
        txtBP_C = new javax.swing.JTextField();
        txtHSL_C = new javax.swing.JTextField();
        cbbMaNV = new javax.swing.JComboBox<>();
        cbbCV = new javax.swing.JComboBox<>();
        lblMaCV = new javax.swing.JLabel();
        lblMaBP = new javax.swing.JLabel();
        cbbBP = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        dpNgay = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoTri = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("BIẾN ĐỘNG NHÂN SỰ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chức vụ cũ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bộ phận cũ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Lương cơ bản cũ");

        lblCV_C.setForeground(new java.awt.Color(204, 204, 204));

        lblBP_C.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Chức vụ mới");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Bộ phận mới");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Lương cơ bản mới");

        txtHSL_M.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ngày hiệu lực");

        txtCV_C.setEditable(false);

        txtBP_C.setEditable(false);

        txtHSL_C.setEditable(false);
        txtHSL_C.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cbbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMaNVItemStateChanged(evt);
            }
        });

        cbbCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbCV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCVItemStateChanged(evt);
            }
        });

        lblMaCV.setForeground(new java.awt.Color(204, 204, 204));

        lblMaBP.setForeground(new java.awt.Color(204, 204, 204));

        cbbBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbBP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbBPItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tên nhân viên");

        txtTen.setEditable(false);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCV_C)
                                .addComponent(txtBP_C)
                                .addComponent(cbbMaNV, 0, 142, Short.MAX_VALUE))
                            .addComponent(txtHSL_C, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(14, 14, 14)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbBP, 0, 179, Short.MAX_VALUE)
                                    .addComponent(txtHSL_M))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBP_C, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbCV, javax.swing.GroupLayout.Alignment.LEADING, 0, 180, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCV_C, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dpNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330)
                .addComponent(lblMaBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(lblMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29))
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCV_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtBP_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtHSL_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))))
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHSL_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(dpNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(lblCV_C, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28))
                                .addComponent(lblBP_C, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblBoTri.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblBoTri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBoTri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoTriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoTri);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_save_40px.png"))); // NOI18N
        btnThem.setText("Lưu");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_40px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 367, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        StringBuilder sb = new StringBuilder();
        if (sb.length() > 0) {
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        try {
            BienDongNhanSu newnv = SetBienDong();
            BienDongDAO dao = new BienDongDAO();
            BienDongNhanSu nv = dao.FindNhanVien(cbbMaNV.getSelectedItem().toString(), fm.format(dpNgay.getDate()));
            if (MessageDialogHelper.showConfirm(home, "Tiếp tục thưc hiện?", "Thông báo") == JOptionPane.NO_OPTION) {
                return;
            }
            if (nv != null) {
                if (dao.update(newnv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            } else {
                if (dao.insert(newnv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            }
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbbMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMaNVItemStateChanged
        try {
            String MaNV = cbbMaNV.getSelectedItem().toString();
            HopDongDAO dao = new HopDongDAO();
            HopDongLaoDong nv = dao.FindNV(MaNV);
            LyLichDAO lldao = new LyLichDAO();
            LyLich ll = lldao.FindNhanVien(MaNV);
            if (nv != null) {
                lblCV_C.setText(nv.getMaCV());
                txtCV_C.setText(nv.getTenCV());
                txtBP_C.setText(nv.getTenBP());
                lblBP_C.setText(nv.getMaBP());
                txtTen.setText(nv.getTenNV());
                txtHSL_C.setText(Format.FormatNumber(nv.getLuongCoBan()));
                txtHSL_M.setText(Format.FormatNumber(nv.getLuongCoBan()));
                cbbCV.setSelectedItem(nv.getTenCV());
                cbbBP.setSelectedItem(nv.getTenBP());
                if (ll.getHinhAnh() != null) {
                    Image img = ImageHelper.createImageFromBytoArray(ll.getHinhAnh(), "jpg");
                    lblImage.setIcon(new ImageIcon(img));
                    personalImage = ll.getHinhAnh();
                } else {
                    personalImage = null;
                    ImageIcon icon = null;
                    switch (ll.getGioiTinh()) {
                        case 0:
                            icon = new ImageIcon(getClass().getResource("/Image/icons8_female_profile_80px.png"));
                            break;
                        case 1:
                            icon = new ImageIcon(getClass().getResource("/Image/icons8_male_user_80px.png"));
                            break;
                    }
                    lblImage.setIcon(icon);
                }
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cbbMaNVItemStateChanged

    private void tblBoTriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoTriMouseClicked
        try {
            int row = tblBoTri.getSelectedRow();
            if (row >= 0) {
                String MaNV = (String) tblBoTri.getValueAt(row, 0);
                String Ngay = (String) tblBoTri.getValueAt(row, 1);
                BienDongDAO dao = new BienDongDAO();
                BienDongNhanSu nv = dao.FindNhanVien(MaNV, Ngay);
                if (nv != null) {
                    cbbMaNV.setSelectedItem(nv.getMaNV());
                    dpNgay.setDate(fm.parse(Ngay));
                    cbbCV.setSelectedItem(nv.getTenCV_M());
                    cbbBP.setSelectedItem(nv.getTenBP_M());
                    txtHSL_M.setText(Format.FormatNumber(nv.getHeSoLuong_M()));
                    txtCV_C.setText(nv.getTenCV_C());
                    txtBP_C.setText(nv.getTenBP_C());
                    txtHSL_C.setText(Format.FormatNumber(nv.getHeSoLuong_C()));
                }
            }
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblBoTriMouseClicked

    private void cbbCVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCVItemStateChanged
        ChucVuDAO dao = new ChucVuDAO();
        ChucVu cv = new ChucVu();
        try {
            cv = dao.FindCVByName(cbbCV.getSelectedItem().toString());
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                lblMaCV.setText(cv.getMaCV());
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cbbCVItemStateChanged

    private void cbbBPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbBPItemStateChanged
        BoPhanDAO dao = new BoPhanDAO();
        BoPhan bp = new BoPhan();
        try {
            bp = dao.FindBPByName(cbbBP.getSelectedItem().toString());
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                lblMaBP.setText(bp.getMaPB());
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cbbBPItemStateChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb = new StringBuilder();
        if (sb.length() > 0) {
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        if (MessageDialogHelper.showConfirm(home, "Tiếp tục xóa?", "Thông báo") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            BienDongDAO dao = new BienDongDAO();
            if (dao.delete(cbbMaNV.getSelectedItem().toString(), fm.format(dpNgay.getDate()))) {
                MessageDialogHelper.showMessage(home, "Đã xóa", "Thông báo");
                LoadTable();
            } else {
                MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
            }
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private BienDongNhanSu SetBienDong() {
        BienDongNhanSu bd = new BienDongNhanSu();
        bd.setMaNV(cbbMaNV.getSelectedItem().toString());
        bd.setNgayHieuLuc(fm.format(dpNgay.getDate()));
        bd.setMaBP_C(lblBP_C.getText());
        bd.setMaCV_C(lblCV_C.getText());
        bd.setHeSoLuong_C(Format.RemoveFormat(txtHSL_C.getText()));
        bd.setMaBP_M(lblMaBP.getText());
        bd.setMaCV_M(lblMaCV.getText());
        bd.setHeSoLuong_M(Format.RemoveFormat(txtHSL_M.getText()));
        return bd;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbBP;
    private javax.swing.JComboBox<String> cbbCV;
    private javax.swing.JComboBox<String> cbbMaNV;
    private com.toedter.calendar.JDateChooser dpNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBP_C;
    private javax.swing.JLabel lblCV_C;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMaBP;
    private javax.swing.JLabel lblMaCV;
    private javax.swing.JTable tblBoTri;
    private javax.swing.JTextField txtBP_C;
    private javax.swing.JTextField txtCV_C;
    private javax.swing.JTextField txtHSL_C;
    private javax.swing.JTextField txtHSL_M;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
