/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.BoPhanDAO;
import Helpers.MessageDialogHelper;
import Helpers.ShareData;
import Helpers.TableDesign;
import Model.BoPhan;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class FrBoPhan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrBoPhan
     */
    public FrBoPhan() {
        initComponents();
        initTable();
        LoadTable();
        processLoginSuccessful();
    }
    
    
    private DefaultTableModel tblmodel;
    SimpleDateFormat fm=new SimpleDateFormat("yyyy-MM-dd");
    private Home home;
    private void initTable(){
        tblmodel =new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"Mã bộ phận","Tên bộ phận","Email","Số điện thoại","Ghi chú"});
        tblBoPhan.setModel(tblmodel);
        TableDesign.Design(tblBoPhan);
    }
    
    private void LoadTable(){
        try{
            BoPhanDAO dao=new BoPhanDAO();
            List<BoPhan> list;
            list = dao.FindAllBoPhan();
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaPB(),it.getTenPB(),it.getEmail(),it.getSDT(),it.getGhiChu()});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaBP = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtTenBP = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoPhan = new javax.swing.JTable();
        btnThm = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("BỘ PHẬN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã bộ phận");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ghi chú");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên bộ phận");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenBP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblBoPhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBoPhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoPhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoPhan);

        btnThm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_save_40px.png"))); // NOI18N
        btnThm.setText("Lưu");
        btnThm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThmActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_40px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThm)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThmActionPerformed
        StringBuilder sb=new StringBuilder();
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        try{
            BoPhan nv=setBoPhan();
            BoPhanDAO dao=new BoPhanDAO();
            BoPhan bp = dao.FindBPByMa(txtMaBP.getText());
            if (MessageDialogHelper.showConfirm(home, "Tiếp tục thưc hiện?", "Thông báo") == JOptionPane.NO_OPTION) {
                return;
            }
            if (bp != null) {
                if (dao.update(nv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                    New();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            } else {
                if (dao.insert(nv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                    New();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            }
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnThmActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb=new StringBuilder();
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirm(home, "Tiếp tục xóa?", "Thông báo")==JOptionPane.NO_OPTION){
            return;
        }
        try {
            BoPhanDAO dao = new BoPhanDAO();
            dao.delete(txtMaBP.getText().trim());
            MessageDialogHelper.showMessage(home, "Đã xóa", "Thông báo");
            LoadTable();
            New();
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblBoPhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoPhanMouseClicked
        try{
            int row= tblBoPhan.getSelectedRow();
            if(row>=0){
                String MaBP=(String)tblBoPhan.getValueAt(row, 0);
                BoPhanDAO dao= new BoPhanDAO();
                BoPhan nv=dao.FindBPByMa(MaBP);
                if( nv!=null){
                    txtMaBP.setText(nv.getMaPB());
                    txtTenBP.setText(nv.getTenPB());
                    txtemail.setText(nv.getEmail());
                    txtGhiChu.setText(nv.getGhiChu());
                    txtSDT.setText(nv.getSDT());
                }
            }
        }catch (Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblBoPhanMouseClicked

    private void processLoginSuccessful(){
        if(ShareData.login.getDep().equals("All")){
            btnThm.setEnabled(true);
            btnXoa.setEnabled(true);
        } else {
            btnThm.setEnabled(false);
            btnXoa.setEnabled(false);
            btnThm.setToolTipText("Tài khoản không được cấp quyền ");
            btnXoa.setToolTipText("Tài khoản không được cấp quyền ");
        }
    }
    
    private void New(){
        txtMaBP.setText("");
        txtGhiChu.setText("");
        txtSDT.setText("");
        txtTenBP.setText("");
        txtemail.setText("");
    }
    
    private BoPhan setBoPhan(){
        BoPhan bp=new BoPhan();
        bp.setMaBP(txtMaBP.getText());
        bp.setTenPB(txtTenBP.getText());
        bp.setGhiChu(txtGhiChu.getText());
        bp.setSDT(txtSDT.getText());
        bp.setEmail(txtemail.getText());
        return bp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThm;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBoPhan;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaBP;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenBP;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
