/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.BoPhanDAO;
import DAO.ChamCongDAO;
import DAO.HopDongDAO;
import DAO.NhanVienDAO;
import Helpers.MessageDialogHelper;
import Helpers.TableDesign;
import Model.BoPhan;
import Model.ChamCong;
import Model.HopDongLaoDong;
import Model.NhanVien;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class FrChamCong extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrChamCong
     */
    public FrChamCong() {
        initComponents();
        LoadComboBox();
        ItemEvent ItemEvent = null;
        cbbBPItemStateChanged(ItemEvent);
        initTable();
        LoadTable();
        DesignTable();
    }
    
    SimpleDateFormat fm= new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat month= new SimpleDateFormat("MM");
    SimpleDateFormat year= new SimpleDateFormat("yyyy");
    
    private DefaultTableModel tblmodel;
    
    private Home home;
    private void initTable(){
//        Table Nhân viên
        tblmodel =new DefaultTableModel(){
            @Override
            public Class<?> getColumnClass(int column){
                switch(column){
                    case 0:
                        return String.class;
                    case 1:
                        return String.class;
                    case 2:
                        return String.class;
                    case 3:
                        return String.class;
                    case 4:
                        return Boolean.class;
                    default:
                        return String.class;
                }
            }
        };
        tblmodel.setColumnIdentifiers(new String[]{"Mã nhân viên","Tên nhân viên","Tên bộ phận","Tên chức vụ","Chọn"});
        tblNhanVien.setModel(tblmodel);
        tblNhanVien.setBackground(Color.WHITE);
        TableDesign.Design(tblNhanVien);
    }
    
    private void DesignTable(){
        tblNhanVien.getColumnModel().getColumn(1).setPreferredWidth(150);
    }
    
    private void LoadTable(){
        try{
            HopDongDAO daonv = new HopDongDAO();
            List<HopDongLaoDong> list;
            BoPhanDAO bpdao=new BoPhanDAO();
            BoPhan bp=bpdao.FindBPByName(cbbBP.getSelectedItem().toString());
            tblmodel.setRowCount(0);
            if (cbbBP.getSelectedItem() == "Tất cả") {
                list = daonv.FindAll();
            } else {
                list = daonv.FindAllByDep(bp.getMaPB());
            }
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),it.getTenNV(),it.getTenBP(),it.getTenCV(),true});
            });
        }catch(Exception ex){
            
        }
    }
    private void LoadComboBox(){
        try{
            cbbBP.removeAllItems();
            BoPhanDAO dao3=new BoPhanDAO();
            List<BoPhan> list3= dao3.FindAllBoPhan();
            cbbBP.addItem("Tất cả");
            list3.forEach(it -> {
                cbbBP.addItem(it.getTenPB());
            });
            cbbLoaiChamCong.removeAllItems();
            String LoaiChamCong[]={"đi làm","công tác","nghỉ có lương","nghỉ không lương"}; 
            for (int i = 0; i < LoaiChamCong.length; i++) {
                cbbLoaiChamCong.addItem(LoaiChamCong[i]);
            }
        }catch(Exception ex){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnChamCong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbBP = new javax.swing.JComboBox<>();
        dpNgayChamCong = new com.toedter.calendar.JDateChooser();
        btnMoi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbbLoaiChamCong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnTongCC = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CHẤM CÔNG");

        tblNhanVien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);

        btnChamCong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChamCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_view_schedule_40px.png"))); // NOI18N
        btnChamCong.setText("Chấm công");
        btnChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCongActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bộ phận");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ngày");

        cbbBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbBP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbBPItemStateChanged(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_restart_40px.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Loại chấm công");

        cbbLoaiChamCong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên");

        txtTenNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_16px.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnTongCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTongCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_view_schedule_40px.png"))); // NOI18N
        btnTongCC.setText("Tổng chấm công");
        btnTongCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTongCC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(62, 62, 62)
                                        .addComponent(cbbBP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbLoaiChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dpNgayChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTenNV))
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbbBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dpNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbLoaiChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChamCong)
                    .addComponent(btnMoi)
                    .addComponent(btnTongCC))
                .addGap(180, 180, 180))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbBPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbBPItemStateChanged
        LoadTable();
    }//GEN-LAST:event_cbbBPItemStateChanged

    private void btnChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCongActionPerformed
        String LoaiChamCong[]={"đi làm","công tác","nghỉ có lương","nghỉ không lương"};
        String KyTu[]={"C","CT","CL","KL"};
        try{
            int n=0;
            if (MessageDialogHelper.showConfirm(home, "Tiếp tục thưc hiện?", "Thông báo") == JOptionPane.NO_OPTION) {
                return;
            }
            for(int i=0;i<tblNhanVien.getRowCount();i++){
                boolean check=(Boolean)tblNhanVien.getValueAt(i, 4);
                ChamCong cc=new ChamCong();
                ChamCongDAO daocc=new ChamCongDAO();
                cc.setMaNV(tblNhanVien.getValueAt(i, 0).toString());
                cc.setNgayChamCong(fm.format(dpNgayChamCong.getDate()));
                for (int j = 0; j < LoaiChamCong.length; j++) {
                    if (cbbLoaiChamCong.getSelectedItem().toString().equals(LoaiChamCong[j])) {
                        cc.setGhiChu(KyTu[j]);
                        break;
                    }
                }
                ChamCong checkcc=daocc.FindNhanVien(tblNhanVien.getValueAt(i, 0).toString(), fm.format(dpNgayChamCong.getDate()));
                
                if (check) {
                    if(checkcc != null) {
                        daocc.update(cc);
                    } else {
                        daocc.insert(cc);
                    }
                    tblmodel.removeRow(i);
                    i--;
                    n++;
                }
            }
            MessageDialogHelper.showMessage(home, "Chấm công thành công " + n + " người", "Thông báo");
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnChamCongActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked

    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        LoadTable();
        cbbLoaiChamCong.setSelectedItem("đi làm");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            NhanVienDAO dao = new NhanVienDAO();
            List<NhanVien> list;
            list = dao.FindNameNhanVien(txtTenNV.getText());
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(), it.getTenNV(), it.getTenPB(), it.getTenCV(), true});
            });
            tblmodel.fireTableDataChanged();
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnTongCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongCCActionPerformed
        
        FrmTongChamCong frm = new FrmTongChamCong(Integer.parseInt(month.format(dpNgayChamCong.getDate())) , Integer.parseInt(year.format(dpNgayChamCong.getDate())));
        frm.setVisible(true);
    }//GEN-LAST:event_btnTongCCActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamCong;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTongCC;
    private javax.swing.JComboBox<String> cbbBP;
    private javax.swing.JComboBox<String> cbbLoaiChamCong;
    private com.toedter.calendar.JDateChooser dpNgayChamCong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
