/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ChucVuDAO;
import Helpers.MessageDialogHelper;
import Helpers.ShareData;
import Model.ChucVu;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class FrChucVu extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrChucVu
     */
    public FrChucVu() {
        initComponents();
        initTable();
        LoadTable();
        processLoginSuccessful();
    }
    
    private DefaultTableModel tblmodel;
    SimpleDateFormat fm=new SimpleDateFormat("yyyy-MM-dd");
    private Home home;
    private void initTable(){
        tblmodel =new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"Mã chức vụ","Tên chức vụ","Ghi chú"});
        tblBoPhan.setModel(tblmodel);
    }
    
    private void LoadTable(){
        try{
            ChucVuDAO dao=new ChucVuDAO();
            List<ChucVu> list;
            list = dao.FindAllChucVu();
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaCV(),it.getTenCV(),it.getGhiChu()});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaCV = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtTenCV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoPhan = new javax.swing.JTable();
        btnThm = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CHỨC VỤ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã chức vụ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ghi chú");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên chức vụ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tblBoPhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBoPhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoPhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoPhan);

        btnThm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_save_40px.png"))); // NOI18N
        btnThm.setText("Lưu");
        btnThm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThmActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_40px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThm)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThm)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBoPhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoPhanMouseClicked
        try{
            int row= tblBoPhan.getSelectedRow();
            if(row>=0){
                String TenCV=(String)tblBoPhan.getValueAt(row, 1);
                ChucVuDAO dao=new ChucVuDAO();
                ChucVu nv=dao.FindCVByName(TenCV);
                if( nv!=null){
                    txtMaCV.setText(nv.getMaCV());
                    txtTenCV.setText(nv.getTenCV());
                    txtGhiChu.setText(nv.getGhiChu());
                }
            }
        }catch (Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblBoPhanMouseClicked

    private void btnThmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThmActionPerformed
        StringBuilder sb=new StringBuilder();
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        try{
            ChucVu nv=setChucVu();
            ChucVuDAO dao=new ChucVuDAO();
            ChucVu cv=dao.FindCVByID(txtMaCV.getText());
            if (MessageDialogHelper.showConfirm(home, "Tiếp tục thưc hiện?", "Thông báo") == JOptionPane.NO_OPTION) {
                return;
            }
            if (cv != null) {
                if (dao.update(nv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                    New();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            } else {
                if (dao.insert(nv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                    New();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            }
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnThmActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb=new StringBuilder();
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirm(home, "Tiếp tục xóa?", "Thông báo")==JOptionPane.NO_OPTION){
            return;
        }
        try{
            ChucVuDAO dao = new ChucVuDAO();
            dao.delete(txtMaCV.getText().trim());
            MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
            LoadTable();
            New();
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void processLoginSuccessful(){
        if(ShareData.login.getDep().equals("All") ){
            btnThm.setEnabled(true);
            btnXoa.setEnabled(true);
        } else {
            btnThm.setEnabled(false);
            btnXoa.setEnabled(false);
            btnThm.setToolTipText("Tài khoản không được cấp quyền ");
            btnXoa.setToolTipText("Tài khoản không được cấp quyền ");
        }
    }
    
    private void New(){
        txtMaCV.setText("");
        txtGhiChu.setText("");
        txtTenCV.setText("");
    }
    
    private ChucVu setChucVu(){
        ChucVu bp=new ChucVu();
        bp.setMaCV(txtMaCV.getText());
        bp.setTenCV(txtTenCV.getText());
        bp.setGhiChu(txtGhiChu.getText());
        return bp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThm;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBoPhan;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaCV;
    private javax.swing.JTextField txtTenCV;
    // End of variables declaration//GEN-END:variables
}
