/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import DAO.BoPhanDAO;
import DAO.ChucVuDAO;
import DAO.HopDongDAO;
import DAO.LyLichDAO;
import Helpers.DatabaseHelper;
import Helpers.Format;
import Helpers.MessageDialogHelper;
import Helpers.TableDesign;
import Model.BoPhan;
import Model.ChucVu;
import Model.HopDongLaoDong;
import Model.LyLich;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author QUYNH
 */
public class FrHopDongLaoDong extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrHopDongLaoDong
     */
    public FrHopDongLaoDong() {
        initComponents();
        LoadComboBox();
        initTable();
        LoadTable();
        DesignTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHopDong = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbCV = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbBP = new javax.swing.JComboBox<>();
        cbbLoai = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        dpNgayBatDau = new com.toedter.calendar.JDateChooser();
        dpNgayKetThuc = new com.toedter.calendar.JDateChooser();
        txtLuongCB = new javax.swing.JTextField();
        txtPhuCap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dpNgayKy = new com.toedter.calendar.JDateChooser();
        cbbMaNV = new javax.swing.JComboBox<>();
        btnReport = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("HỢP ĐỒNG LAO ĐỘNG");

        tblHopDong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHopDongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblHopDongMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblHopDong);

        btnLuu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_save_40px.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_cv_40px.png"))); // NOI18N
        btnThem1.setText("Lý lịch");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên");

        cbbCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Chức vụ ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bộ phận ");

        cbbBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbbLoaiKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Loại hợp đồng lao dộng");

        txtTen.setEditable(false);
        txtTen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        dpNgayBatDau.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        dpNgayKetThuc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtLuongCB.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLuongCB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLuongCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongCBActionPerformed(evt);
            }
        });

        txtPhuCap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPhuCap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPhuCap.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPhuCapInputMethodTextChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Phụ cấp");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Lương cơ bản");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Ngày kết thúc");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ngày hiệu lực");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tên nhân viên");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Ngày ký");

        dpNgayKy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        cbbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMaNVItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dpNgayKy, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(cbbLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbCV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbBP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(24, 24, 24)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dpNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dpNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(539, 539, 539))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLuongCB)
                            .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel2)
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbbBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel12)
                                            .addComponent(txtLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dpNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(dpNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(cbbCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpNgayKy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(35, 35, 35))
        );

        btnReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_print_40px.png"))); // NOI18N
        btnReport.setText("In");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_40px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox2, 0, 0, Short.MAX_VALUE)
                .addGap(1191, 1191, 1191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnThem1)
                    .addComponent(btnReport)
                    .addComponent(btnXoa))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1392, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    SimpleDateFormat fm= new SimpleDateFormat("yyyy-MM-dd");
    private Home home;
    private DefaultTableModel tblmodel;
    
    private void initTable(){
        tblmodel =new DefaultTableModel();
        String[] header={"Mã nhân viên",
                         "Tên nhân viên",
                         "Ngày ký",
                         "Ngày bắt đầu",
                         "Ngày kết thúc",
                         "Tên chức vụ",
                         "Tên phòng ban",
                         "Lương cơ bản",
                         "Phụ cấp",
                         "Loại hợp đồng",
                         "Bảo hiểm"};
        tblmodel.setColumnIdentifiers(header);
        tblHopDong.setModel(tblmodel);
        TableDesign.Design(tblHopDong);
    }
    
    private void DesignTable(){
        //định dạng số sang bên phải
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tblHopDong.setModel(tblmodel);
        tblHopDong.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        tblHopDong.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
        //chiều cao header
//        tblHopDong.getTableHeader().setPreferredSize(new Dimension(tblHopDong.getColumnModel().getTotalColumnWidth(), 40));
        //kích thước cột
        tblHopDong.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblHopDong.getColumnModel().getColumn(0).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblHopDong.getColumnModel().getColumn(2).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(3).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(4).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(5).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(6).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(7).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(8).setPreferredWidth(160);
        tblHopDong.getColumnModel().getColumn(9).setPreferredWidth(200);
    }
    
    private void LoadTable(){
        try{
            HopDongDAO dao=new HopDongDAO();
            List<HopDongLaoDong> list;
            list = dao.FindAll();
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),
                                            it.getTenNV(),
                                            it.getNgayKy(),
                                            it.getNgayBatDau(),
                                            it.getNgayKetThuc(),
                                            it.getTenCV(),
                                            it.getTenBP(),
                                            Format.FormatNumber(it.getLuongCoBan()),
                                            Format.FormatNumber(it.getPhuCap()),
                                            it.getLoai(),
                                            it.getBaoHiem()==1?"Có":"Không"});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }
    
    private void LoadComboBox() {
        try {
            String[] type={"Không xác định thời hạn","Xác định thời hạn","Thử việc","Theo thời vụ"};
            cbbLoai.removeAllItems();
            for (String type1 : type) {
                cbbLoai.addItem(type1);
            }
            
            cbbBP.removeAllItems();
            BoPhanDAO dao1=new BoPhanDAO();
            List<BoPhan> list1= dao1.FindAllBoPhan();
            list1.forEach(it -> {
                cbbBP.addItem(it.getTenPB());
            });
            
            cbbCV.removeAllItems();
            ChucVuDAO dao2=new ChucVuDAO();
            List<ChucVu> list2=dao2.FindAllChucVu();
            list2.forEach(it -> {
                cbbCV.addItem(it.getTenCV());
            });
            
            cbbMaNV.removeAllItems();
            LyLichDAO daonv=new LyLichDAO();
            List<LyLich> listnv=daonv.FindAll();
            listnv.forEach(it -> {
                cbbMaNV.addItem(it.getMaNV());
            });
        } catch (Exception ex) {
        }
    }
    
    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        FrmLyLich f = new FrmLyLich(cbbMaNV.getSelectedItem().toString());
        f.setVisible(true);
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            HopDongDAO dao=new HopDongDAO();
            HopDongLaoDong hd=dao.FindNV(cbbMaNV.getSelectedItem().toString(), fm.format(dpNgayBatDau.getDate()), fm.format(dpNgayKetThuc.getDate()));
            HopDongLaoDong hdmoi=createHopDong();
            if (MessageDialogHelper.showConfirm(home, "Tiếp tục thưc hiện?", "Thông báo") == JOptionPane.NO_OPTION) {
                return;
            }
            if (hd != null) {
                if (dao.update(hdmoi)) {
                    MessageDialogHelper.showMessage(this, "Đã lưu", "Thông báo");
                    LoadTable();
                } else {
                    MessageDialogHelper.showError(this, "Không thể lưu", "Lỗi");
                }
            } else {
                if (dao.insert(hdmoi)) {
                    MessageDialogHelper.showMessage(this, "Đã lưu", "Thông báo");
                    LoadTable();
                } else {
                    MessageDialogHelper.showError(this, "Không thể lưu", "Lỗi");
                }
            }
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tblHopDongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopDongMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHopDongMouseEntered

    private void tblHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopDongMouseClicked
        int row=tblHopDong.getSelectedRow();
        FindNV(tblHopDong.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblHopDongMouseClicked

    private void txtLuongCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongCBActionPerformed

    }//GEN-LAST:event_txtLuongCBActionPerformed

    private void cbbLoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbLoaiKeyReleased

    }//GEN-LAST:event_cbbLoaiKeyReleased

    private void cbbMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMaNVItemStateChanged
//        String MaNV = cbbMaNV.getSelectedItem().toString();
//        if (MaNV == null) {
//            MaNV = "NV001";
//        }
//        FindNV(MaNV);
    }//GEN-LAST:event_cbbMaNVItemStateChanged

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        try {
            java.sql.Connection conn= DatabaseHelper.openConnection();
            String link="C:\\Users\\QUYNH\\OneDrive - UFM\\ThucTapTotNghiep\\QuanLyNhanSu\\src\\Report\\HopdongLaoDong.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(link);
            HashMap param=new HashMap();
            param.put("MaNV", cbbMaNV.getSelectedItem().toString());
            JasperPrint jp=JasperFillManager.fillReport(jr,param, conn);
            JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void txtPhuCapInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPhuCapInputMethodTextChanged

    }//GEN-LAST:event_txtPhuCapInputMethodTextChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb=new StringBuilder();
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirm(home, "Tiếp tục xóa?", "Thông báo")==JOptionPane.NO_OPTION){
            return;
        }
        try{
            HopDongDAO dao=new HopDongDAO();
            if(dao.delete(cbbMaNV.getSelectedItem().toString(), fm.format(dpNgayBatDau.getDate()))){
                MessageDialogHelper.showMessage(home, "Đã xóa", "Thông báo");
                LoadTable();
            }else {
                MessageDialogHelper.showError(home, "Không thể xóa", "Lỗi");
            }
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void FindNV(String MaNV){
        try {
            HopDongDAO dao=new HopDongDAO();
            HopDongLaoDong nv = dao.FindNV(MaNV);
            if( nv!=null){
                cbbMaNV.setSelectedItem(nv.getMaNV());
                txtTen.setText(nv.getTenNV());
                cbbCV.setSelectedItem(nv.getTenCV());
                cbbBP.setSelectedItem(nv.getTenBP());
                cbbLoai.setSelectedItem(nv.getLoai());
                dpNgayBatDau.setDate(fm.parse(nv.getNgayBatDau()));
                dpNgayKetThuc.setDate(fm.parse(nv.getNgayKetThuc()));
                dpNgayKy.setDate(fm.parse(nv.getNgayKy()));
                txtLuongCB.setText(String.valueOf(Format.FormatNumber(nv.getLuongCoBan())));
                txtPhuCap.setText(String.valueOf(Format.FormatNumber(nv.getPhuCap())));
            } else{
                LyLichDAO lldao=new LyLichDAO();
                LyLich ll= lldao.FindNhanVien(MaNV);
                txtTen.setText(ll.getTenNV());
                txtLuongCB.setText("");
                txtPhuCap.setText("");
            }
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }
    
    private HopDongLaoDong createHopDong() {
        try {
            ChucVuDAO cvdao=new ChucVuDAO();
            BoPhanDAO bpdao=new BoPhanDAO();
            HopDongLaoDong hdmoi = new HopDongLaoDong();
            ChucVu cv=cvdao.FindCVByName(cbbCV.getSelectedItem().toString());
            BoPhan bp=bpdao.FindBPByName(cbbBP.getSelectedItem().toString());
            
            hdmoi.setMaNV(cbbMaNV.getSelectedItem().toString());
            hdmoi.setNgayBatDau(fm.format(dpNgayBatDau.getDate()));
            hdmoi.setNgayKetThuc(fm.format(dpNgayKetThuc.getDate()));
            hdmoi.setNgayKy(fm.format(dpNgayKy.getDate()));
            hdmoi.setLuongCoBan(Format.RemoveFormat(txtLuongCB.getText()));
            hdmoi.setMaBP(bp.getMaPB());
            hdmoi.setMaCV(cv.getMaCV());
            hdmoi.setLoai(cbbLoai.getSelectedItem().toString());
            hdmoi.setPhuCap(Format.RemoveFormat(txtPhuCap.getText()));
            return hdmoi;
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
        return null;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbBP;
    private javax.swing.JComboBox<String> cbbCV;
    private javax.swing.JComboBox<String> cbbLoai;
    private javax.swing.JComboBox<String> cbbMaNV;
    private com.toedter.calendar.JDateChooser dpNgayBatDau;
    private com.toedter.calendar.JDateChooser dpNgayKetThuc;
    private com.toedter.calendar.JDateChooser dpNgayKy;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHopDong;
    private javax.swing.JTextField txtLuongCB;
    private javax.swing.JTextField txtPhuCap;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
