/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.KyLuatDAO;
import DAO.LyLichDAO;
import DAO.NhanVienDAO;
import Helpers.Format;
import Helpers.MessageDialogHelper;
import Helpers.TableDesign;
import Model.KyLuat;
import Model.LyLich;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class FrKyLuat extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrKyLuat
     */
    public FrKyLuat() {
        initComponents();
        LoadComboBox();
        initTable();
        LoadTable();
        DesignTable();
    }
    
    private DefaultTableModel tblmodel;
    SimpleDateFormat fm=new SimpleDateFormat("yyyy-MM-dd");
    private Home home;
    private void initTable(){
        tblmodel =new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"Mã nhân viên","Ngày kỷ luật","Mức kỷ luật","Ghi chú"});
        tblKyLuat.setModel(tblmodel);
        TableDesign.Design(tblKyLuat);
    }
    
    private void LoadTable(){
        try{
            KyLuatDAO dao=new KyLuatDAO();
            List<KyLuat> list;
            list = dao.FindAllBoTri();
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),it.getNgayKyLuat(),Format.FormatNumber(it.getMucKyLuat()),it.getGhiChu()});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }
    private void DesignTable(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tblKyLuat.setModel(tblmodel);
        tblKyLuat.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
    }
    private void LoadComboBox(){
        try{
            cbbMaNV.removeAllItems();
            NhanVienDAO dao3=new NhanVienDAO();
            List<Model.NhanVien> list3= dao3.FindAllNhanVien();
            list3.forEach(it -> {
                cbbMaNV.addItem(it.getMaNV());
            });
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMucKyLuat = new javax.swing.JTextField();
        dpNgay = new com.toedter.calendar.JDateChooser();
        txtGhiChu = new javax.swing.JTextField();
        cbbMaNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKyLuat = new javax.swing.JTable();
        btnThm = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("KỶ LUẬT");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ngày kỷ luật");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mức kỷ luật");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ghi chú");

        txtMucKyLuat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cbbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMaNVItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên nhân viên");

        txtTenNV.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGhiChu)
                            .addComponent(txtMucKyLuat)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbbMaNV, 0, 127, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenNV)
                    .addComponent(dpNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtMucKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tblKyLuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKyLuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKyLuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKyLuat);

        btnThm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_save_40px.png"))); // NOI18N
        btnThm.setText("Lưu");
        btnThm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThmActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_40px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThm)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThm)
                    .addComponent(btnXoa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThmActionPerformed
        StringBuilder sb=new StringBuilder();
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        try{
            KyLuat nv=setKyLuat();
            KyLuatDAO dao=new KyLuatDAO();
            KyLuat kl=dao.FindNhanVien(cbbMaNV.getSelectedItem().toString(), fm.format(dpNgay.getDate()));
            if (kl != null) {
                if (dao.update(nv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                    New();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            } else {
                if (dao.insert(nv)) {
                    MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                    LoadTable();
                    New();
                } else {
                    MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
                }
            }
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnThmActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb=new StringBuilder();
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirm(home, "Tiếp tục xóa?", "Thông báo")==JOptionPane.NO_OPTION){
            return;
        }
        try{
            KyLuatDAO dao=new KyLuatDAO();
            if(dao.delete(cbbMaNV.getSelectedItem().toString(),fm.format(dpNgay.getDate()))){
                MessageDialogHelper.showMessage(home, "Đã lưu", "Thông báo");
                LoadTable();
                New();
            }else {
                MessageDialogHelper.showError(home, "Không thể lưu", "Lỗi");
            }
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbbMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMaNVItemStateChanged
        try{
            String MaNV=cbbMaNV.getSelectedItem().toString();
            LyLichDAO dao= new LyLichDAO();
            LyLich nv=dao.FindNhanVien(MaNV);
            if( nv!=null){
                txtTenNV.setText(nv.getTenNV());
            } else{
            }
        }catch (Exception ex){
        }
    }//GEN-LAST:event_cbbMaNVItemStateChanged

    private void tblKyLuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKyLuatMouseClicked
        try{
            int row= tblKyLuat.getSelectedRow();
            if(row>=0){
                String MaNV=(String)tblKyLuat.getValueAt(row, 0);
                String Ngay=(String)tblKyLuat.getValueAt(row, 1);
                KyLuatDAO dao= new KyLuatDAO();
                KyLuat nv=dao.FindNhanVien(MaNV,Ngay);
                if( nv!=null){
                    cbbMaNV.setSelectedItem(nv.getMaNV());
                    dpNgay.setDate(fm.parse(nv.getNgayKyLuat()));
                    txtMucKyLuat.setText(Format.FormatNumber(nv.getMucKyLuat()));
                    txtGhiChu.setText(nv.getGhiChu());
                }
            }
        }catch (Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblKyLuatMouseClicked

    
    private void New(){
        txtMucKyLuat.setText("");
        txtGhiChu.setText("");
    }
    
    private KyLuat setKyLuat(){
        KyLuat kt=new KyLuat();
        kt.setMaNV(cbbMaNV.getSelectedItem().toString());
        kt.setMucKyLuat(Format.RemoveFormat(txtMucKyLuat.getText()));
        kt.setNgayKyLuat(fm.format(dpNgay.getDate()));
        kt.setGhiChu(txtGhiChu.getText());
        return kt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThm;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaNV;
    private com.toedter.calendar.JDateChooser dpNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKyLuat;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMucKyLuat;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
