/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.BienDongDAO;
import DAO.BoPhanDAO;
import DAO.ChucVuDAO;
import DAO.NhanVienDAO;
import Helpers.DatabaseHelper;
import Helpers.ImageHelper;
import Helpers.MessageDialogHelper;
import Model.BienDongNhanSu;
import Model.BoPhan;
import Model.ChucVu;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class FrmBaoCaoBienDong extends javax.swing.JInternalFrame {

    /**
     * Creates new form RPBienDong
     */
    public FrmBaoCaoBienDong() {
        initComponents();
        LoadComboBox();
        initTable();
        LoadTable();
    }
    
    private DefaultTableModel tblmodel;
    private byte[] persionalImage;
    SimpleDateFormat fm=new SimpleDateFormat("yyyy-MM-dd");
    private Home home;
    private void initTable(){
        tblmodel =new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"Mã nhân viên","Ngày hiện lực","Tên chức vụ cũ","Tên phòng ban cũ","Hệ số lương cũ","Tên chức vụ mới","Tên phòng ban mới","Hệ số lương mới"});
        tblBoTri.setModel(tblmodel);
    }
    
    private void LoadTable(){
        try{
            BienDongDAO dao=new BienDongDAO();
            List<BienDongNhanSu> list;
            list = dao.FindAllBoTri();
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),it.getNgayHieuLuc(),it.getTenCV_C(),it.getTenBP_C(),it.getHeSoLuong_C(),it.getTenCV_M(),it.getTenBP_M(),it.getHeSoLuong_M()});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }
    private void LoadComboBox(){
        try{
            cbbBP.removeAllItems();
            BoPhanDAO dao1=new BoPhanDAO();
            List<BoPhan> list1= dao1.FindAllBoPhan();
            list1.forEach(it -> {
                cbbBP.addItem(it.getTenPB());
            });
            
            cbbCV.removeAllItems();
            ChucVuDAO dao2=new ChucVuDAO();
            List<ChucVu> list2=dao2.FindAllChucVu();
            list2.forEach(it -> {
                cbbCV.addItem(it.getTenCV());
            });
            
            cbbMaNV.removeAllItems();
            NhanVienDAO dao3=new NhanVienDAO();
            List<Model.NhanVien> list3= dao3.FindAllNhanVien();
            list3.forEach(it -> {
                cbbMaNV.addItem(it.getMaNV());
            });
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCV_C = new javax.swing.JLabel();
        lblBP_C = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHSL_M = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCV_C = new javax.swing.JTextField();
        txtBP_C = new javax.swing.JTextField();
        txtHSL_C = new javax.swing.JTextField();
        cbbMaNV = new javax.swing.JComboBox<>();
        cbbCV = new javax.swing.JComboBox<>();
        lblMaCV = new javax.swing.JLabel();
        lblMaBP = new javax.swing.JLabel();
        cbbBP = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        dpNgay = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoTri = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chức vụ cũ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bộ phận cũ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Hệ số lương cũ");

        lblCV_C.setForeground(new java.awt.Color(204, 204, 204));

        lblBP_C.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Chức vụ mới");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Bộ phận mới");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Hệ số lương mới");

        txtHSL_M.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ngày hiệu lực");

        txtCV_C.setEditable(false);

        txtBP_C.setEditable(false);

        txtHSL_C.setEditable(false);
        txtHSL_C.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cbbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMaNVItemStateChanged(evt);
            }
        });

        cbbCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbCV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCVItemStateChanged(evt);
            }
        });

        lblMaCV.setForeground(new java.awt.Color(204, 204, 204));

        lblMaBP.setForeground(new java.awt.Color(204, 204, 204));

        cbbBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbBP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbBPItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tên nhân viên");

        txtTen.setEditable(false);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-camo-cream-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCV_C)
                                .addComponent(txtBP_C)
                                .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHSL_C, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCV_C, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBP_C, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbBP, 0, 118, Short.MAX_VALUE)
                            .addComponent(cbbCV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTen)
                            .addComponent(txtHSL_M))
                        .addGap(5, 5, 5)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(dpNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(lblCV_C, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(lblBP_C, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCV_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBP_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHSL_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(lblMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHSL_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dpNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tblBoTri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBoTri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoTriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoTri);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_print_40px.png"))); // NOI18N
        jButton1.setText("In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(186, 186, 186)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMaNVItemStateChanged
        try{
            String MaNV=cbbMaNV.getSelectedItem().toString();
            NhanVienDAO dao= new NhanVienDAO();
            Model.NhanVien nv=dao.FindNhanVien(MaNV);
            if( nv!=null){
                lblCV_C.setText(nv.getMaCV());
                txtCV_C.setText(nv.getTenCV());
                txtBP_C.setText(nv.getTenPB());
                lblBP_C.setText(nv.getMaBP());
                txtTen.setText(nv.getTenNV());
                txtHSL_C.setText(String.valueOf(nv.getLuongCoBan()));
                if(nv.getHinhAnh()!=null){
                    Image img=ImageHelper.createImageFromBytoArray(nv.getHinhAnh(), "jpg");
                    lblImage.setIcon(new ImageIcon(img));
                    persionalImage=nv.getHinhAnh();
                } else{
//                    persionalImage=null;
//                    ImageIcon icon=new ImageIcon(getClass().getResource("/image/icons8-camo-cream-64.png"));
//                    lblImage.setIcon(icon);
                }
            } else{
            } 
        }catch (Exception ex){
        }
    }//GEN-LAST:event_cbbMaNVItemStateChanged

    private void cbbCVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCVItemStateChanged
        ChucVuDAO dao= new ChucVuDAO();
        ChucVu cv=new ChucVu();
        try {
            cv=dao.FindCVByName(cbbCV.getSelectedItem().toString());
            if(evt.getStateChange()==ItemEvent.SELECTED){
                lblMaCV.setText(cv.getMaCV());
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cbbCVItemStateChanged

    private void cbbBPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbBPItemStateChanged
        BoPhanDAO dao= new BoPhanDAO();
        BoPhan bp=new BoPhan();
        try {
            bp=dao.FindBPByName(cbbBP.getSelectedItem().toString());
            if(evt.getStateChange()==ItemEvent.SELECTED){
                lblMaBP.setText(bp.getMaPB());
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cbbBPItemStateChanged

    private void tblBoTriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoTriMouseClicked
        try{
            int row= tblBoTri.getSelectedRow();
            if(row>=0){
                String MaNV=(String)tblBoTri.getValueAt(row, 0);
                String Ngay=(String)tblBoTri.getValueAt(row, 1);
                BienDongDAO dao= new BienDongDAO();
                BienDongNhanSu nv=dao.FindNhanVien(MaNV,Ngay);
                if( nv!=null){
                    cbbMaNV.setSelectedItem(nv.getMaNV());
                    dpNgay.setDate(fm.parse(Ngay));
                    cbbCV.setSelectedItem(nv.getTenCV_M());
                    cbbBP.setSelectedItem(nv.getTenBP_M());
                    txtHSL_M.setText(String.valueOf(nv.getHeSoLuong_M()));
                    txtCV_C.setText(nv.getTenCV_C());
                    txtBP_C.setText(nv.getTenBP_C());
                    txtHSL_C.setText(String.valueOf(nv.getHeSoLuong_C()));
                }
            }
        }catch (Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblBoTriMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            java.sql.Connection conn= DatabaseHelper.openConnection();
            String link="C:\\Users\\QUYNH\\OneDrive - UFM\\ThucTapTotNghiep\\QuanLyNhanSu\\src\\Report\\BienDong.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(link);
            HashMap param=new HashMap();
            param.put("MaNV", cbbMaNV.getSelectedItem().toString());
            JasperPrint jp=JasperFillManager.fillReport(jr,param, conn);
            JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbBP;
    private javax.swing.JComboBox<String> cbbCV;
    private javax.swing.JComboBox<String> cbbMaNV;
    private com.toedter.calendar.JDateChooser dpNgay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBP_C;
    private javax.swing.JLabel lblCV_C;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMaBP;
    private javax.swing.JLabel lblMaCV;
    private javax.swing.JTable tblBoTri;
    private javax.swing.JTextField txtBP_C;
    private javax.swing.JTextField txtCV_C;
    private javax.swing.JTextField txtHSL_C;
    private javax.swing.JTextField txtHSL_M;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
