/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.NhanVienDAO;
import Helpers.Format;
import Helpers.ImageHelper;
import Helpers.MessageDialogHelper;
import Helpers.TableDesign;
import Model.NhanVien;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class FrTimNhanVien extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmTimNhanVien
     */
    public FrTimNhanVien() {
        initComponents();
        initTable();
        LoadTable();
        Design();
    }
    private DefaultTableModel tblmodel;
    private byte[] personalImage;
    private Home home;
    private void initTable(){
        tblmodel =new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"Mã nhân viên","Tên nhân viên","Tên chức vụ","Tên phòng ban","Lương cơ bản"});
        tblNhanVien.setModel(tblmodel);
    }
    
    private void LoadTable(){
        try{
            NhanVienDAO dao=new NhanVienDAO();
            List<Model.NhanVien> list;
            list = dao.FindAllNhanVien();
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),it.getTenNV(),it.getTenCV(),it.getTenPB(),Format.FormatNumber(it.getLuongCoBan())});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }
    
    private void Design(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tblNhanVien.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        TableDesign.Design(tblNhanVien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHSL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSearchID = new javax.swing.JButton();
        btnSearchName = new javax.swing.JButton();
        btnSearchDept = new javax.swing.JButton();
        btnSearchCV = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        lblMaCV = new javax.swing.JLabel();
        lblMaBP = new javax.swing.JLabel();
        txtCV = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnLyLich = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setInheritsPopupMenu(true);

        txtMaNV.setEnabled(false);
        txtMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaNVKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaNVKeyReleased(evt);
            }
        });

        txtTenNV.setEnabled(false);
        txtTenNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenNVKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chức vụ ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bộ phận ");

        txtHSL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHSL.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Lương cơ bản");

        btnSearchID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchID.setText("Tìm theo mã");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });

        btnSearchName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchName.setText("Tìm theo tên");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        btnSearchDept.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchDept.setText("Tìm theo phòng");
        btnSearchDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDeptActionPerformed(evt);
            }
        });

        btnSearchCV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchCV.setText("Tìm theo chức vụ");
        btnSearchCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCVActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchCV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchDept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearchID)
                .addGap(18, 18, 18)
                .addComponent(btnSearchName)
                .addGap(18, 18, 18)
                .addComponent(btnSearchDept)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCV)
                .addGap(18, 18, 18)
                .addComponent(btnNew)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMaCV.setForeground(new java.awt.Color(204, 204, 204));

        lblMaBP.setForeground(new java.awt.Color(204, 204, 204));

        txtCV.setEnabled(false);
        txtCV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCVKeyReleased(evt);
            }
        });

        txtBP.setEnabled(false);
        txtBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBPKeyReleased(evt);
            }
        });

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHSL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMaBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(lblMaBP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtHSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        btnLyLich.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLyLich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_cv_40px.png"))); // NOI18N
        btnLyLich.setText("Lý lịch");
        btnLyLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLyLichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnLyLich)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLyLich)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
        New();
        txtMaNV.setEnabled(true);
        txtTenNV.setEnabled(false);
        txtCV.setEnabled(false);
        txtBP.setEnabled(false);
        
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void txtMaNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNVKeyReleased
        try{
            NhanVienDAO dao=new NhanVienDAO();
            List<NhanVien> list;
            list = dao.FindNhanVienlist(txtMaNV.getText());
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                                tblmodel.addRow(new Object[]{it.getMaNV(),it.getTenNV(),it.getTenCV(),it.getTenPB(),Format.FormatNumber(it.getLuongCoBan())});
            });
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }//GEN-LAST:event_txtMaNVKeyReleased

    private void txtTenNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenNVKeyReleased
        try {
            NhanVienDAO dao = new NhanVienDAO();
            List<NhanVien> list;
            list = dao.FindNameNhanVien(txtTenNV.getText());
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(), it.getTenNV(), it.getTenCV(), it.getTenPB(), Format.FormatNumber(it.getLuongCoBan())});
            });
            tblmodel.fireTableDataChanged();
        } catch (Exception ex) {
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }//GEN-LAST:event_txtTenNVKeyReleased

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        New();
        txtMaNV.setEnabled(false);
        txtTenNV.setEnabled(true);
        txtCV.setEnabled(false);
        txtBP.setEnabled(false);
    }//GEN-LAST:event_btnSearchNameActionPerformed

    private void btnSearchCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCVActionPerformed
        New();
        txtMaNV.setEnabled(false);
        txtTenNV.setEnabled(false);
        txtCV.setEnabled(true);
        txtBP.setEnabled(false);
    }//GEN-LAST:event_btnSearchCVActionPerformed

    private void btnSearchDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDeptActionPerformed
        New();
        txtMaNV.setEnabled(false);
        txtTenNV.setEnabled(false);
        txtCV.setEnabled(false);
        txtBP.setEnabled(true);
    }//GEN-LAST:event_btnSearchDeptActionPerformed

    private void txtCVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCVKeyReleased
        try{
            NhanVienDAO dao=new NhanVienDAO();
            List<NhanVien> list;
            list = dao.FindCVNhanVienlist(txtCV.getText());
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),it.getTenNV(),it.getTenCV(),it.getTenPB(),Format.FormatNumber(it.getLuongCoBan())});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }//GEN-LAST:event_txtCVKeyReleased

    private void txtBPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBPKeyReleased
        try{
            NhanVienDAO dao=new NhanVienDAO();
            
            List<NhanVien> list;
            list = dao.FindBPNhanVienlist(txtBP.getText());
            tblmodel.setRowCount(0);
            list.forEach(it -> {
                tblmodel.addRow(new Object[]{it.getMaNV(),it.getTenNV(),it.getTenCV(),it.getTenPB(),Format.FormatNumber(it.getLuongCoBan())});
            });
            tblmodel.fireTableDataChanged();
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.toString(), "Lỗi");
        }
    }//GEN-LAST:event_txtBPKeyReleased

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       New();
       LoadTable();
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtMaNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNVKeyPressed
        
    }//GEN-LAST:event_txtMaNVKeyPressed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        try{
            int row= tblNhanVien.getSelectedRow();
            if(row>=0){
                String MaNV=(String)tblNhanVien.getValueAt(row, 0);
                NhanVienDAO dao= new NhanVienDAO();
                NhanVien nv=dao.FindNhanVien(MaNV);
                if( nv!=null){
                    txtMaNV.setText(nv.getMaNV());
                    txtCV.setText(nv.getTenCV());
                    txtBP.setText(nv.getTenPB());
                    txtTenNV.setText(nv.getTenNV());
                    txtHSL.setText(String.valueOf(Format.FormatNumber(nv.getLuongCoBan())));
                    if(nv.getHinhAnh()!=null){
                        Image img=ImageHelper.createImageFromBytoArray(nv.getHinhAnh(), "jpg");
                        lblImage.setIcon(new ImageIcon(img));
                        personalImage=nv.getHinhAnh();
                    } else{
                        personalImage=null;
                        ImageIcon icon=null;
                        switch (nv.getGioiTinh()) {
                            case 0:
                                icon=new ImageIcon(getClass().getResource("/Image/icons8_female_profile_80px.png"));
                                break;
                            case 1:
                                icon=new ImageIcon(getClass().getResource("/Image/icons8_male_user_80px.png"));
                                break;
                            default:
                                
                        }
                        lblImage.setIcon(icon);
                    }
                }
            }
        }catch (Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnLyLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLyLichActionPerformed
        FrmLyLich f = new FrmLyLich(txtMaNV.getText());
        f.setVisible(true);
    }//GEN-LAST:event_btnLyLichActionPerformed

    private void New(){
        txtMaNV.setText("");
        txtTenNV.setText("");
        txtCV.setText("");
        txtBP.setText("");
        txtHSL.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLyLich;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSearchCV;
    private javax.swing.JButton btnSearchDept;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMaBP;
    private javax.swing.JLabel lblMaCV;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtCV;
    private javax.swing.JTextField txtHSL;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
