/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;

import Helpers.DatabaseHelper;
import Helpers.ShareData;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GOLD ̣̣̣̣9999
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
//        processLoginSuccessful();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        pndesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HeThong = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiCreateUser = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jmiLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiChucVu = new javax.swing.JMenuItem();
        jmiBoPhan = new javax.swing.JMenuItem();
        NghiepVu = new javax.swing.JMenu();
        jmiNhanVien = new javax.swing.JMenuItem();
        jmiLyLich = new javax.swing.JMenuItem();
        jmiKhenThuong = new javax.swing.JMenuItem();
        jmiKyLuat = new javax.swing.JMenuItem();
        jmiHopDong = new javax.swing.JMenuItem();
        jmiBienDong = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiChamCong = new javax.swing.JMenuItem();
        jmiLuong = new javax.swing.JMenuItem();
        TimKiem = new javax.swing.JMenu();
        jmiSearchNV = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        BaoCao = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jmiRPBP = new javax.swing.JMenuItem();
        jmiRPCV = new javax.swing.JMenuItem();
        jmiRPBienDong = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG NHÂN SỰ - TIỀN LƯƠNG");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pndesktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỆ THỐNG NHÂN SỰ - TIỀN LƯƠNG");

        pndesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pndesktopLayout = new javax.swing.GroupLayout(pndesktop);
        pndesktop.setLayout(pndesktopLayout);
        pndesktopLayout.setHorizontalGroup(
            pndesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1798, Short.MAX_VALUE)
                .addContainerGap())
        );
        pndesktopLayout.setVerticalGroup(
            pndesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndesktopLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addContainerGap(568, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pndesktop)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pndesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        HeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_start_menu_16px_1.png"))); // NOI18N
        HeThong.setText("Hệ thống");
        HeThong.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        HeThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeThongActionPerformed(evt);
            }
        });

        jMenuItem9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem9.setText("Sao lưu dữ liệu");
        HeThong.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem10.setText("Xuất dữ liệu");
        HeThong.add(jMenuItem10);
        HeThong.add(jSeparator1);

        jmiCreateUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiCreateUser.setText("Tạo tài khoản");
        jmiCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateUserActionPerformed(evt);
            }
        });
        HeThong.add(jmiCreateUser);

        jMenuItem15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem15.setText("Đổi mật khẩu");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        HeThong.add(jMenuItem15);

        jMenuItem14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem14.setText("Phân quyền");
        HeThong.add(jMenuItem14);

        jmiLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiLogout.setText("Đăng xuất");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        HeThong.add(jmiLogout);

        jMenuBar1.add(HeThong);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_folder_16px.png"))); // NOI18N
        jMenu2.setText("Danh mục");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmiChucVu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiChucVu.setText("Chức vụ");
        jmiChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiChucVuMouseClicked(evt);
            }
        });
        jmiChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChucVuActionPerformed(evt);
            }
        });
        jMenu2.add(jmiChucVu);

        jmiBoPhan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiBoPhan.setText("Bộ phận");
        jmiBoPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBoPhanActionPerformed(evt);
            }
        });
        jMenu2.add(jmiBoPhan);

        jMenuBar1.add(jMenu2);

        NghiepVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_crowd_16px_1.png"))); // NOI18N
        NghiepVu.setText("Nhân sự");
        NghiepVu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmiNhanVien.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiNhanVien.setText("Nhân viên");
        jmiNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiNhanVienMouseClicked(evt);
            }
        });
        jmiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhanVienActionPerformed(evt);
            }
        });
        NghiepVu.add(jmiNhanVien);

        jmiLyLich.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiLyLich.setText("Lý lịch");
        jmiLyLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLyLichActionPerformed(evt);
            }
        });
        NghiepVu.add(jmiLyLich);

        jmiKhenThuong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiKhenThuong.setText("Khen Thưởng");
        jmiKhenThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKhenThuongActionPerformed(evt);
            }
        });
        NghiepVu.add(jmiKhenThuong);

        jmiKyLuat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiKyLuat.setText("Kỷ Luật");
        jmiKyLuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKyLuatActionPerformed(evt);
            }
        });
        NghiepVu.add(jmiKyLuat);

        jmiHopDong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiHopDong.setText("Hợp đồng lao dộng");
        jmiHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHopDongActionPerformed(evt);
            }
        });
        NghiepVu.add(jmiHopDong);

        jmiBienDong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiBienDong.setText("Biến động nhân sự");
        jmiBienDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBienDongActionPerformed(evt);
            }
        });
        NghiepVu.add(jmiBienDong);

        jMenuBar1.add(NghiepVu);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_money_bag_16px.png"))); // NOI18N
        jMenu3.setText("Lương");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmiChamCong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiChamCong.setText("Chấm công");
        jmiChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChamCongActionPerformed(evt);
            }
        });
        jMenu3.add(jmiChamCong);

        jmiLuong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiLuong.setText("Lương nhân viên");
        jmiLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLuongActionPerformed(evt);
            }
        });
        jMenu3.add(jmiLuong);

        jMenuBar1.add(jMenu3);

        TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_16px.png"))); // NOI18N
        TimKiem.setText("Tìm kiếm");
        TimKiem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });

        jmiSearchNV.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiSearchNV.setText("Nhân viên");
        jmiSearchNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchNVActionPerformed(evt);
            }
        });
        TimKiem.add(jmiSearchNV);

        jMenuItem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem1.setText("Chấm công nhân viên");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        TimKiem.add(jMenuItem1);

        jMenuBar1.add(TimKiem);

        BaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_graph_16px.png"))); // NOI18N
        BaoCao.setText("Báo cáo");
        BaoCao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaoCaoActionPerformed(evt);
            }
        });

        jMenu1.setText("Danh sách nhân viên");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem11.setText("Tất cả");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jmiRPBP.setText("Theo phòng ban");
        jmiRPBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRPBPActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRPBP);

        jmiRPCV.setText("Theo chức vụ");
        jmiRPCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRPCVActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRPCV);

        BaoCao.add(jMenu1);

        jmiRPBienDong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmiRPBienDong.setText("Biến động nhân sự");
        jmiRPBienDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRPBienDongActionPerformed(evt);
            }
        });
        BaoCao.add(jmiRPBienDong);

        jMenuBar1.add(BaoCao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        Login login=new Login(this,true);
        login.setVisible(true);
        
        processLoginSuccessful();
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void HeThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeThongActionPerformed

    }//GEN-LAST:event_HeThongActionPerformed

    private void jmiNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiNhanVienMouseClicked

    }//GEN-LAST:event_jmiNhanVienMouseClicked

    private void jmiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhanVienActionPerformed
        FrNhanVien f=new FrNhanVien();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiNhanVienActionPerformed

    private void jmiLyLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLyLichActionPerformed
        FrLyLich f=new FrLyLich();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiLyLichActionPerformed

    private void jmiBienDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBienDongActionPerformed
        FrBienDong f=new FrBienDong();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiBienDongActionPerformed

    private void jmiChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChamCongActionPerformed
        FrChamCong f=new FrChamCong();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiChamCongActionPerformed

    private void jmiKhenThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKhenThuongActionPerformed
        FrKhenThuong f=new FrKhenThuong();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiKhenThuongActionPerformed

    private void jmiLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLuongActionPerformed
        FrThongTinLuong f=new FrThongTinLuong();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiLuongActionPerformed

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiemActionPerformed

    private void jmiKyLuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKyLuatActionPerformed
        FrKyLuat f=new FrKyLuat();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiKyLuatActionPerformed

    private void jmiSearchNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchNVActionPerformed
        FrTimNhanVien f=new FrTimNhanVien();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiSearchNVActionPerformed

    private void jmiBoPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBoPhanActionPerformed
        FrBoPhan f=new FrBoPhan();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiBoPhanActionPerformed

    private void jmiChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiChucVuMouseClicked
        FrChucVu f=new FrChucVu();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiChucVuMouseClicked

    private void jmiCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCreateUserActionPerformed
        TaoTaiKhoan f=new TaoTaiKhoan(this,true);
        f.setVisible(true);
    }//GEN-LAST:event_jmiCreateUserActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        try {
            java.sql.Connection conn= DatabaseHelper.openConnection();
            String link="C:\\Users\\QUYNH\\OneDrive - UFM\\ThucTapTotNghiep\\QuanLyNhanSu\\src\\Report\\RPNVAll.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(link);
            JasperPrint jp=JasperFillManager.fillReport(jr,null, conn);
            JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Login login=new Login(this, true);
        login.setVisible(true);
        processLoginSuccessful();
    }//GEN-LAST:event_formWindowOpened

    private void jmiRPBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRPBPActionPerformed
        FrmBaoCaoBP f=new FrmBaoCaoBP();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiRPBPActionPerformed

    private void jmiRPCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRPCVActionPerformed
        FrmBaoCaoCV f=new FrmBaoCaoCV();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiRPCVActionPerformed

    private void jmiChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChucVuActionPerformed
       FrChucVu f=new FrChucVu();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiChucVuActionPerformed

    private void BaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaoCaoActionPerformed
        
    }//GEN-LAST:event_BaoCaoActionPerformed

    private void jmiRPBienDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRPBienDongActionPerformed
        FrmBaoCaoBienDong f=new FrmBaoCaoBienDong();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiRPBienDongActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHopDongActionPerformed
        FrHopDongLaoDong f=new FrHopDongLaoDong();
        pndesktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jmiHopDongActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        DoiMatKhau f=new DoiMatKhau(this,true);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void processLoginSuccessful(){
        if(ShareData.login.getRole().equals("admin") || ShareData.login.getDep().equals("HR") && ShareData.login.getRole().equals("manager")){
            jmiCreateUser.setEnabled(true);
        } else {
            jmiCreateUser.setEnabled(false);
            jmiCreateUser.setToolTipText("Tài khoản không được cấp quyền ");
        }

        if (ShareData.login.getDep().equals("HR") || ShareData.login.getDep().equals("All")) {
            jmiLuong.setEnabled(true);
            NghiepVu.setEnabled(true);
        } else {
            jmiLuong.setEnabled(false);
            jmiLuong.setToolTipText("Tài khoản không được cấp quyền ");
        }

        if (ShareData.login.getDep().equals("Accounting") || ShareData.login.getDep().equals("All")) {
            jmiLuong.setEnabled(true);
            jmiKhenThuong.setEnabled(true);
            jmiKyLuat.setEnabled(true);
        } else {
            jmiLuong.setEnabled(false);
            jmiLuong.setToolTipText("Tài khoản không được cấp quyền ");
        }
        if(ShareData.login.getDep().equals("Accounting")){
            jmiNhanVien.setEnabled(false);
            jmiLyLich.setEnabled(false);
            jmiHopDong.setEnabled(false);
            jmiChamCong.setEnabled(false);
            jmiBienDong.setEnabled(false);
            jmiChamCong.setToolTipText("Tài khoản không được cấp quyền ");
            jmiKyLuat.setToolTipText("Tài khoản không được cấp quyền ");
            jmiKhenThuong.setToolTipText("Tài khoản không được cấp quyền ");
            jmiNhanVien.setToolTipText("Tài khoản không được cấp quyền ");
            jmiLyLich.setToolTipText("Tài khoản không được cấp quyền ");
            jmiHopDong.setToolTipText("Tài khoản không được cấp quyền ");
            jmiBienDong.setToolTipText("Tài khoản không được cấp quyền ");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BaoCao;
    private javax.swing.JMenu HeThong;
    private javax.swing.JMenu NghiepVu;
    private javax.swing.JMenu TimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmiBienDong;
    private javax.swing.JMenuItem jmiBoPhan;
    private javax.swing.JMenuItem jmiChamCong;
    private javax.swing.JMenuItem jmiChucVu;
    private javax.swing.JMenuItem jmiCreateUser;
    private javax.swing.JMenuItem jmiHopDong;
    private javax.swing.JMenuItem jmiKhenThuong;
    private javax.swing.JMenuItem jmiKyLuat;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiLuong;
    private javax.swing.JMenuItem jmiLyLich;
    private javax.swing.JMenuItem jmiNhanVien;
    private javax.swing.JMenuItem jmiRPBP;
    private javax.swing.JMenuItem jmiRPBienDong;
    private javax.swing.JMenuItem jmiRPCV;
    private javax.swing.JMenuItem jmiSearchNV;
    private javax.swing.JDesktopPane pndesktop;
    // End of variables declaration//GEN-END:variables
}
