/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.NguoiDungDAO;
import Helpers.DataValidator;
import Helpers.MessageDialogHelper;
import Model.User;

/**
 *
 * @author DELL
 */
public class TaoTaiKhoan extends javax.swing.JDialog {

    private Home home;
    /**
     * Creates new form TaoTaiKhoan
     */
    public TaoTaiKhoan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtPasswword = new javax.swing.JTextField();
        rdbadmin = new javax.swing.JRadioButton();
        rdbuser = new javax.swing.JRadioButton();
        rdbmanager = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtCreateUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rdbHR = new javax.swing.JRadioButton();
        rdbAccounting = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TẠO TÀI KHOẢN");

        jLabel2.setText("Tên người dùng");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Quyền hạn");

        buttonGroup1.add(rdbadmin);
        rdbadmin.setText("Điều hành");
        rdbadmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbadminStateChanged(evt);
            }
        });
        rdbadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbadminActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbuser);
        rdbuser.setText("Nhân viên");

        buttonGroup1.add(rdbmanager);
        rdbmanager.setText("Quản lý");
        rdbmanager.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbmanagerItemStateChanged(evt);
            }
        });
        rdbmanager.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbmanagerStateChanged(evt);
            }
        });
        rdbmanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbmanagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtusername)
                        .addComponent(txtPasswword, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rdbadmin)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbmanager)
                            .addComponent(rdbuser))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdbadmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbmanager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(rdbuser)
                .addContainerGap())
        );

        txtCreateUser.setText("Tạo");
        txtCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCreateUser)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCreateUser)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jLabel5.setText("Bộ phận");

        buttonGroup2.add(rdbHR);
        rdbHR.setText("Nhân sự");

        buttonGroup2.add(rdbAccounting);
        rdbAccounting.setText("Kế toán");
        rdbAccounting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAccountingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbAccounting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbHR))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdbHR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbAccounting)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateUserActionPerformed
        StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(sb, txtusername, "Tên người dùng không được để trống");
        DataValidator.validateEmpty(sb, txtPasswword, "Mật khẩu được để trống");
        
        if(sb.length()>0){
            MessageDialogHelper.showError(home, sb.toString(), "Lỗi");
            return;
        }
        
        try{
            User user=new User();
            user.setUserName(txtusername.getText());
            user.setPassword(txtPasswword.getText());
            //Set role
            String role="";
            if(rdbadmin.isSelected()){
                role="admin";
            } else if (rdbuser.isSelected()){
                role="user";
            } else if (rdbmanager.isSelected()){
                role="manager";
            }
            user.setRole(role);
            //Set Department
            String Dep="All";
            if(rdbHR.isSelected()){
                Dep="HR";
            } else if (rdbAccounting.isSelected()){
                Dep="Accounting";
            }
            user.setDep(Dep);
            NguoiDungDAO dao=new NguoiDungDAO();
            if(dao.insert(user)){
                MessageDialogHelper.showMessage(home, "Đã tạo", "Thông báo");
            }else {
                MessageDialogHelper.showError(home, "Không thể tạo", "Lỗi");
            }
        }catch(Exception ex){
            MessageDialogHelper.showError(home, ex.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_txtCreateUserActionPerformed

    private void rdbmanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbmanagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbmanagerActionPerformed

    private void rdbadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbadminActionPerformed

    private void rdbAccountingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAccountingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbAccountingActionPerformed

    private void rdbmanagerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbmanagerStateChanged
        if (rdbadmin.isSelected()) {
            jPanel3.setVisible(false);
        } else if (rdbuser.isSelected() || rdbmanager.isSelected()) {
            jPanel3.setVisible(true);
        }
    }//GEN-LAST:event_rdbmanagerStateChanged

    private void rdbmanagerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbmanagerItemStateChanged
        
    }//GEN-LAST:event_rdbmanagerItemStateChanged

    private void rdbadminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbadminStateChanged
        if (rdbadmin.isSelected()) {
                jPanel3.setVisible(false);
        } else if (rdbuser.isSelected() || rdbmanager.isSelected()) {
                jPanel3.setVisible(true);
        }
    }//GEN-LAST:event_rdbadminStateChanged

    public void New(){
        txtusername.setText("");
        txtPasswword.setText("");
        buttonGroup1.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaoTaiKhoan dialog = new TaoTaiKhoan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdbAccounting;
    private javax.swing.JRadioButton rdbHR;
    private javax.swing.JRadioButton rdbadmin;
    private javax.swing.JRadioButton rdbmanager;
    private javax.swing.JRadioButton rdbuser;
    private javax.swing.JButton txtCreateUser;
    private javax.swing.JTextField txtPasswword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
